baseurl: "/"
languageCode: "zh-CN"
title: "考研 1234"
theme: qaqland
copyright: |
  &copy; 2021 -- {Year} [kaoyan1234](https://kaoyan1234.com) | Email | [Source](https://github.com/qaqland/kaoyan)

permalinks:
  /: /:year/:filename/

menu:
  main:
    - name: 学校
      url: /
    - name: 学科
      url: /tags
    - name: 通用
      url: /通用

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
