baseurl: "/"
languageCode: "zh-CN"
title: "考研 1234"
theme: qaqland
copyright: |
  &copy; 2021 -- {Year} [kaoyan1234](https://kaoyan1234.com) | 微信 | 微博

permalinks:
  /: /:year/:filename/

menu:
  main:
    - name: 学校
      # 文件夹
      url: ""
    - name: 专业
      # 分类
      url: ""
    - name: 标签
      # tags
      url: ""
    - name: 通用
    # 双一流、学科代码

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
